apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: java-service1
  name: java-service1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-service1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-service1
    spec:
      containers:
      - image: java-service1
        imagePullPolicy: Never
        name: java-service1
        resources: {}
status: {}
---
