apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-service1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-service1-pod
  strategy: {}
  template:
    metadata:
      labels:
        app: java-service1-pod
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
        instrumentation.opentelemetry.io/container-names: "java-service1"
    spec:
      containers:
      - image: java-service1
        imagePullPolicy: Never
        name: java-service1