#!/bin/bash
kafka-topics.sh --create --bootstrap-server broker:29092 --replication-factor 1 --partitions 1 --topic $1 --config "cleanup.policy=compact" --config "delete.retention.ms=100" --config "segment.ms=100" --config "min.cleanable.dirty.ratio=0.01"
